#!/usr/bin/env bash
# Made by Jesus Palencia
# Licence: GPL-2
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid

if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debe ser root.\e[00m"
fi

function pause() {
	read -p "$*"
}

if [[ -z $2 ]]; then
	echo -e "\e[00;31mERROR: Faltan parametros.\e[00m"
fi
echo -e "\e[00;1;92mPreparandose para generar llave GPG\e[00m"
echo 'Key-Type: 1' > /tmp/genkey
echo 'Key-Length: 2048' >> /tmp/genkey
echo 'Subkey-Type: 1' >> /tmp/genkey
echo 'Subkey-Length: 2048' >> /tmp/genkey
echo 'Name-Real:' $2 $3 >> /tmp/genkey
echo 'Name-Email:' $4 >> /tmp/genkey
echo 'Expire-Date: 2y' >> /tmp/genkey
echo -e "\e[00;1;92mGenerando llave GPG\e[00m"
script -q /dev/stdout -c 'gpg --batch --gen-key /tmp/genkey' | tee /tmp/listo
millave=$(cat /tmp/listo | grep "gpg: clave" | uniq | awk '{print $3}')
export GPGKEY=$millave
echo ""
echo -e "\e[00;1;92mLlave GPG Generada.\e[00m"
gpg --send-keys --keyserver keyserver.ubuntu.com $millave
echo ""
echo -e "\e[00;1;92mSe envio al keyserver de Ubuntu la siguiente llave: $millave\e[00m"
mihuella=$(gpg --fingerprint $millave | grep "Huella de clave" | cut -c 25-74)
echo -e "\e[00;1;92mFinalizado...\e[00m"

rm -f /run/$(basename $0).pid
exit 0
