#!/usr/bin/env bash
# Made by Jesus Palencia
# Licence: GPL-2
LC_ALL=C

function pause() {
	read -p "$*"
}

pause "Presione cualquier tecla para iniciar o Ctrl + C para finalizar..."

if [[ -d /tmp/llaves ]]; then
	rm -rf /tmp/llaves/*
	rm -f /tmp/genkey
	rm -f /tmp/listo
else
	mkdir -p /tmp/llaves
fi

if [[ -f /tmp/datos.txt ]]; then
	for i in $(cat /tmp/datos.txt); do
		long=$(echo $i | cut -d ":" -f1)
		name=$(echo $i | cut -d ":" -f2)
		last=$(echo $i | cut -d ":" -f3)
		email=$(echo $i | cut -d ":" -f4)
		expi=$(echo $i | cut -d ":" -f5)
		pass=$(echo $i | cut -d ":" -f6)
		echo 'Key-Type: 1' > /tmp/genkey
		echo 'Key-Length:' $long >> /tmp/genkey
		echo 'Subkey-Type: 1' >> /tmp/genkey
		echo 'Subkey-Length:' $long >> /tmp/genkey
		echo 'Name-Real:' $name $last >> /tmp/genkey
		echo 'Name-Comment: No comment' >> /tmp/genkey
		echo 'Name-Email:' $email >> /tmp/genkey
		echo 'Expire-Date:' $expi >> /tmp/genkey
		echo 'Passphrase:' $pass >> /tmp/genkey
		echo '%pubring' $name.$last.pub >> /tmp/genkey
		echo '%secring' $name.$last.sec >> /tmp/genkey
		script -q /dev/stdout -c 'gpg --batch --gen-key /tmp/genkey' | tee /tmp/listo
		millave=$(cat /tmp/listo | grep "gpg: clave" | uniq | awk '{print $3}')
		gpg --export-secret-key -a $millave > /tmp/llaves/$name.$last.private.key
		gpg --export -a $millave > /tmp/llaves/$name.$last.public.key
		# gpg -a -o /tmp/llaves/$name.$last.revoke.asc --command-fd 0 --status-fd 2 --gen-revoke 0x$millave
		if [[ $1 = enviar ]]; then
			gpg --keyserver pgp.mit.edu --send-keys $millave
			gpg --keyserver pool.sks-keyservers.net --send-keys $millave
			gpg --keyserver keyring.debian.org --send-key $millave
			gpg --keyserver keyserver.ubuntu.com --send-keys $millave
			gpg --keyserver keys.fedoraproject.org --send-keys $millave
			gpg --keyserver pgp.uni-mainz.de --send-keys $millave
		fi
		rm -f /tmp/genkey
		rm -f /tmp/listo
	done
else
	echo "ERROR: El archivo /tmp/datos.txt no existe."
	exit 1
fi

echo "Proceso finalizado, vaya a /tmp/llaves para ver los archivos."

exit 0
